### ISSUE TITLE
In Export csv, the line break doesn't work anymore

### ISSUE THREAD

**Issue by tseegers** [centreon/centreon-widget-host-monitoring#28]
Hi, 

With centreon-widget-host-monitoring-1.5.2-1.el6.noarch the export csv worked fine:

![image](https://user-images.githubusercontent.com/13485588/29821657-0636a250-8cc9-11e7-8b7e-46cdf4c862fb.png)

But once you update the widget to version 1.6.0 (centreon-widget-host-monitoring-1.6.0-1.el6.noarch) the line break doesn't work anymore, all the hosts are on the same line:
****
![image](https://user-images.githubusercontent.com/13485588/29821799-7caa9518-8cc9-11e7-8220-e1195207011e.png)

**Comment by thiuyendang** [comment]
OK, checked with centreon-widget :
- service monitoring 1.6.1-2
- host monitoring 1.6.1-1
