### ISSUE TITLE
Icon not displayed in widget

### ISSUE THREAD

**Issue by Hellnino18** [centreon/centreon-widget-host-monitoring#33]
Hi,

Today i have upgraded from Centreon 2.6.6 to 2.8.13 and I have a problem with this widget.  As you can see in the attachment, the path isn't right neither for the URL nor the path for img (Firebug : <img src="//img/icons/chart.png" class="ico-18" title="See Graphs of this host">)

![centreon-bug-host-monitoring](https://user-images.githubusercontent.com/14218330/30861157-240fa2d8-a2ca-11e7-8c16-961196dd9cf1.PNG)

Widget version : 1.6.1

Thanks for your help.

**Comment by julienmathis** [comment]
Hello Nathanael, 

Can you try to clean your browser cache ?

Thanks

**Comment by Hellnino18** [comment]
Hi Julien,

Thanks for your quick response, but I already did this (and another time after your reply) and I have always the same problem.

**Comment by Hellnino18** [comment]
Hi,

Do you have information about this bug plz ?

**Comment by romainchassaigne** [comment]
Hello,

I had the same problem. I changed my httpd config to make my url like this : `https://centreon.mydomain.fr/` but in the widget, all the request url went to `https://centreon.mydomain.fr/centreon`. 

So I made a rewriterules in httpd : 

```
RewriteEngine on
RewriteRule   "^/centreon/(.+)"  "https://centreon.mydomain.fr/$1"
```

Then icons are displayed and links are working well.

**Comment by lpinsivy** [comment]
linked to #38
