### ISSUE TITLE
change field "Duration" from date to time

### ISSUE THREAD

**Issue by barte91** [centreon/centreon-widget-host-monitoring#58]
Hi,

In the new version of widget Host-monitoring 18.10 I see the file d duration in data format like this:

![hostmonitoring](https://user-images.githubusercontent.com/19166634/49095638-320cfd00-f269-11e8-94a4-4d5e178b6a9f.JPG)

 But I prefer see it on duration like in the service-monitoring like this:

![servicemonitoring](https://user-images.githubusercontent.com/19166634/49095652-3b966500-f269-11e8-8deb-df6be2b99422.JPG)

Is possibile?

**Comment by barte91** [comment]
Anyone can help me?

**Comment by sc979** [comment]
Hi @barte91 ,
Your issue as been fixed in this PR : https://github.com/centreon/centreon-widget-host-monitoring/pull/62
I'm closing this issue.
If after updating the widget or directlt applying this PR you still have an issue, please reopen another one.
Best Regards,
sc979
