### ISSUE TITLE
Duration field

### ISSUE THREAD

**Issue by BlackstormFirst** [centreon/centreon-widget-host-monitoring#63]
Hello,

I have 2 servers with CES (one from the OVF, another from the ISO), release 18.10 (18.10.3 actually).

Into my hostgroup monitoring widget, i see sometime the real date (ie. 20 janvier 2019 09:00:25) but sometime i see some thing like "-4140y -1M ago".

I'm using CLAPI into a script to discover computers and automaticaly add them to Centreon and apprently this issue append much time with the script import. My 2nd server have more than 2K computers and actually all imported servers have this issue.

Can you check that please ?

Plugins for CentOS7 are still in 18.10.0, i saw, from the Github, some improvement for widgets these last months, when we will have an update for the widgets please into the CES distrib ? Maybe this issue is already solved but not yet released...

Thanks a lot for your time ^^
Best regards,

**Comment by BlackstormFirst** [comment]
Hi,

Thanks for the update.

The 18.10.1 release fix the issue ^^

**Comment by sc979** [comment]
Hi @BlackstormFirst ,
Thanks for your feedback and sorry for the delay, indeed the PR : https://github.com/centreon/centreon-widget-host-monitoring/pull/62, had fixed this issue.
So I'm closing your issue ;)
Best Regards,
sc979
